title: Ayoyemi Fatokun
logo: Ayoyemi.webp
description: Data Analyst with analytical and resourceful skillsets with a background in collecting, analyzing, and interpreting complex datasets. 
show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
